version: '3.8'

services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - micro-net

  config-server:
    build: ./configuration-server
    container_name: config-server
    ports:
      - "5555:5555"
    depends_on:
      - service-registry
    networks:
      - micro-net

  api-gateway:
    build: ./Api-gateway
    container_name: api-gateway
    ports:
      - "7070:7070"
    depends_on:
      - service-registry
      - config-server
    networks:
      - micro-net

  orders:
    build: ./orders
    container_name: orders
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-db:5432/ordersdb
    - SPRING_DATASOURCE_USERNAME=ordersuser
    - SPRING_DATASOURCE_PASSWORD=orderspass
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    - SPRING_CLOUD_CONFIG_URI=http://config-server:5555
    depends_on:
    - orders-db
    - service-registry
    - config-server
    networks:
      - micro-net

  inventory:
    build: ./Inventory-MicroService
    container_name: inventory
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-db:5432/inventorydb
    - SPRING_DATASOURCE_USERNAME=inventoryuser
    - SPRING_DATASOURCE_PASSWORD=inventorypass
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    - SPRING_CLOUD_CONFIG_URI=http://config-server:5555
    depends_on:
    - inventory-db
    - service-registry
    - config-server
    networks:
      - micro-net

  orders-db:
    image: postgres:15
    container_name: orders-db
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: ordersuser
      POSTGRES_PASSWORD: orderspass
    ports:
    - "5434:5432"  # Map host port 5434 to container port 5432
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypass
    ports:
    - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - micro-net

volumes:
  orders-db-data:
  inventory-db-data:
networks:
  micro-net:
    driver: bridge
